"""CI-03: state the friction policy of the historical fixtures; add current-defaults twins.

Usage:
  python3 tools/ci03/make_fixtures.py --data data --unit-tests build/tests/unit_tests \
      --output /absolute/fresh/dir [--dry-run]

For each of the three CI-03 fixtures this (1) writes
`solver/contact/friction_iterations: 1` into the pinned fixture -- the policy
its stored reference was generated under (upstream's default until RB-10,
2026-09-13), as a text insertion that keeps the file's own formatting --, and
(2) writes a twin `<name>-friction-defaults.json` next to it that inherits the
fixture through `common` and removes that key by a JSON-Patch `remove`, so the
twin runs at the solver's current default and fails loudly if the parent's pin
ever disappears. The twin's `tests` block is generated by the scene harness
itself (`unit_tests run_manifest_env` on a `*` manifest line) on an isolated
copy of the data directory, then written into the twin with the file
pretty-printed; the values are those the harness computed, unchanged. The
generated references are only as good as the checks the record makes on them
(docs/ci-03-validation.md): this script does not decide that they are right.
"""
import argparse
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from ab_runner import FIXTURES, prepare, sha256  # noqa: E402

HISTORICAL_KEY = 'friction_iterations'
HISTORICAL_VALUE = 1


def twin_name(relative):
    p = Path(relative)
    return (p.parent / (p.stem + '-friction-defaults' + p.suffix)).as_posix()


def pin_historical(path, dry_run):
    """Insert the solver block before the "tests" key, keeping the file's indentation."""
    text = path.read_text()
    doc = json.loads(text)
    if doc.get('solver', {}).get('contact', {}).get(HISTORICAL_KEY) == HISTORICAL_VALUE:
        return 'already pinned'
    if 'solver' in doc:
        raise SystemExit(f'{path}: has a solver block; pin it by hand')
    m = re.search(r'^(?P<indent>[ \t]+)"tests": \{', text, re.M)
    if not m:
        raise SystemExit(f'{path}: no "tests" key to anchor on')
    indent = m.group('indent')
    unit = indent  # one level = the top-level key indentation
    block = (f'{indent}"solver": {{\n'
             f'{indent}{unit}"contact": {{\n'
             f'{indent}{unit}{unit}"{HISTORICAL_KEY}": {HISTORICAL_VALUE}\n'
             f'{indent}{unit}}}\n'
             f'{indent}}},\n')
    new_text = text[:m.start()] + block + text[m.start():]
    new_doc = json.loads(new_text)
    assert new_doc['solver']['contact'][HISTORICAL_KEY] == HISTORICAL_VALUE
    for key in doc:
        assert new_doc[key] == doc[key], key
    if not dry_run:
        path.write_text(new_text)
    return 'pinned'


def twin_document(parent_name, tests=None):
    doc = {
        'common': parent_name,
        'patch': [{'op': 'remove', 'path': f'/solver/contact/{HISTORICAL_KEY}'}],
    }
    if tests is not None:
        doc['tests'] = tests
    return doc


def dump(doc):
    return json.dumps(doc, indent=4, sort_keys=True) + '\n'


def generate_tests(args, relative, twin_rel):
    """Run the harness's `*` generation on an isolated copy; return the generated tests block."""
    run_dir = args.output / 'generate' / Path(twin_rel).stem
    if run_dir.exists():
        shutil.rmtree(run_dir)
    run_dir.mkdir(parents=True)
    record = prepare(run_dir, args.data, relative, 'default')  # the (pinned) parent chain + meshes
    twin_copy = run_dir / 'data' / twin_rel
    twin_copy.write_text(dump(twin_document(Path(relative).name)))
    (run_dir / 'manifest.txt').write_text('*' + twin_rel + '\n')
    env = dict(os.environ, POLYFEM_RUN_MANIFEST=str(run_dir / 'manifest.txt'), POLYFEM_RUN_DATA_DIR=str(run_dir / 'data'))
    with open(run_dir / 'run.log', 'w') as log:
        proc = subprocess.run([str(args.unit_tests), 'run_manifest_env'], cwd=run_dir, env=env, stdout=log, stderr=subprocess.STDOUT)
    generated = json.loads(twin_copy.read_text())
    record.update({'twin': twin_rel, 'exit': proc.returncode, 'generated_tests': generated.get('tests')})
    (run_dir / 'run.json').write_text(json.dumps(record, indent=2) + '\n')
    if proc.returncode != 0 or 'tests' not in generated:
        raise SystemExit(f'reference generation failed for {twin_rel}: see {run_dir}/run.log')
    return generated['tests']


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--data', type=Path, required=True, help='the polyfem-data checkout to change (a branch of the fork)')
    parser.add_argument('--unit-tests', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True, help='fresh evidence directory for the generation runs')
    parser.add_argument('--dry-run', action='store_true')
    args = parser.parse_args()
    args.data = args.data.resolve()
    args.unit_tests = args.unit_tests.resolve()
    args.output = args.output.resolve()
    args.output.mkdir(parents=True, exist_ok=True)
    report = {'unit_tests': str(args.unit_tests), 'unit_tests_sha256': sha256(args.unit_tests), 'fixtures': []}
    for slug, relative in FIXTURES.items():
        parent = args.data / relative
        before = sha256(parent)
        status = pin_historical(parent, args.dry_run)
        twin_rel = twin_name(relative)
        entry = {'slug': slug, 'historical': relative, 'historical_status': status, 'historical_sha256_before': before,
                 'historical_sha256_after': sha256(parent), 'twin': twin_rel}
        if not args.dry_run:
            tests = generate_tests(args, relative, twin_rel)
            twin_path = args.data / twin_rel
            twin_path.write_text(dump(twin_document(Path(relative).name, tests)))
            entry['twin_tests'] = tests
            entry['twin_sha256'] = sha256(twin_path)
        report['fixtures'].append(entry)
        print(f"{slug}: historical {status}; twin {twin_rel}{' (dry run)' if args.dry_run else ''}")
    (args.output / 'make_fixtures.json').write_text(json.dumps(report, indent=2) + '\n')


if __name__ == '__main__':
    main()
