# RB-12 run identity: compile the identity of the sources being built into
# the library (src/polyfem/io/BuildInfo.hpp). The data is regenerated by a
# custom target before every build of the library, so it follows the checkouts
# (commit, dirty state, patch hash of the effective PolyFEM / IPC Toolkit /
# PolySolve sources) instead of the configure-time snapshot, and the declared
# dependency pins are read from the recipes next to the effective source
# directories -- the two must never be confused (a local source override
# builds whatever is checked out there, whatever the recipe says).

function(polyfem_add_build_info target)
    find_package(Git QUIET)
    set(git_executable "")
    if(GIT_FOUND)
        set(git_executable "${GIT_EXECUTABLE}")
    endif()

    set(generated_dir "${POLYFEM_GENERATED_INCLUDE_DIR}/polyfem/build_info")
    set(output "${generated_dir}/BuildInfo.cpp")
    file(MAKE_DIRECTORY "${generated_dir}")
    set(script "${PROJECT_SOURCE_DIR}/cmake/polyfem/polyfem_generate_build_info.cmake")

    # Declared pins: what the recipes ask for.
    file(READ "${PROJECT_SOURCE_DIR}/cmake/recipes/ipc_toolkit.cmake" recipe)
    string(REGEX MATCH "CPMAddPackage\\(\"gh:([^#\"]+)#([0-9a-fA-F]+)\"" _ "${recipe}")
    set(ipc_repo "${CMAKE_MATCH_1}")
    set(ipc_pin "${CMAKE_MATCH_2}")
    file(READ "${PROJECT_SOURCE_DIR}/cmake/recipes/polysolve.cmake" recipe)
    string(REGEX MATCH "CPMAddPackage\\(\"gh:([^#\"]+)#([0-9a-fA-F]+)\"" _ "${recipe}")
    set(polysolve_repo "${CMAKE_MATCH_1}")
    set(polysolve_pin "${CMAKE_MATCH_2}")
    file(READ "${PROJECT_SOURCE_DIR}/cmake/recipes/polyfem_data.cmake" recipe)
    string(REGEX MATCH "GIT_TAG +([0-9a-fA-F]+)" _ "${recipe}")
    set(data_pin "${CMAKE_MATCH_1}")

    # Effective sources: where CPM actually took the packages from (a local
    # CPM_<name>_SOURCE override or the download cache).
    set(ipc_source "${CPM_PACKAGE_ipc-toolkit_SOURCE_DIR}")
    set(polysolve_source "${CPM_PACKAGE_polysolve_SOURCE_DIR}")
    set(ipc_override "")
    if(DEFINED CPM_ipc-toolkit_SOURCE)
        set(ipc_override "${CPM_ipc-toolkit_SOURCE}")
    endif()
    set(polysolve_override "")
    if(DEFINED CPM_polysolve_SOURCE)
        set(polysolve_override "${CPM_polysolve_SOURCE}")
    endif()

    set(options "")
    foreach(name
            POLYFEM_WITH_OPTIMIZATION POLYFEM_WITH_PYTHON POLYFEM_WITH_MMG POLYFEM_WITH_CLIPPER
            POLYFEM_WITH_MISO POLYFEM_WITH_ITR POLYFEM_WITH_TRIANGLE POLYFEM_WITH_CUDA
            POLYFEM_PORTABLE_BUILD POLYFEM_CODE_COVERAGE POLYFEM_WITH_TESTS)
        list(APPEND options "${name}=${${name}}")
    endforeach()

    set(cxx_flags_config "")
    set(build_type "${CMAKE_BUILD_TYPE}")
    get_property(multi_config GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
    if(multi_config)
        set(build_type "$<CONFIG>")
        set(cxx_flags_config "unavailable (multi-configuration generator)")
    elseif(CMAKE_BUILD_TYPE)
        string(TOUPPER "${CMAKE_BUILD_TYPE}" config_upper)
        set(cxx_flags_config "${CMAKE_CXX_FLAGS_${config_upper}}")
    endif()

    set(common_args
        "-DOUTPUT=${output}"
        "-DGIT_EXECUTABLE=${git_executable}"
        "-DPOLYFEM_SOURCE_DIR=${PROJECT_SOURCE_DIR}"
        "-DIPC_SOURCE_DIR=${ipc_source}"
        "-DIPC_DECLARED_REPO=${ipc_repo}"
        "-DIPC_DECLARED_PIN=${ipc_pin}"
        "-DIPC_SOURCE_OVERRIDE=${ipc_override}"
        "-DPOLYSOLVE_SOURCE_DIR=${polysolve_source}"
        "-DPOLYSOLVE_DECLARED_REPO=${polysolve_repo}"
        "-DPOLYSOLVE_DECLARED_PIN=${polysolve_pin}"
        "-DPOLYSOLVE_SOURCE_OVERRIDE=${polysolve_override}"
        "-DDATA_DECLARED_PIN=${data_pin}"
        "-DCXX_COMPILER_ID=${CMAKE_CXX_COMPILER_ID}"
        "-DCXX_COMPILER_VERSION=${CMAKE_CXX_COMPILER_VERSION}"
        "-DCXX_COMPILER=${CMAKE_CXX_COMPILER}"
        "-DCXX_FLAGS=${CMAKE_CXX_FLAGS}"
        "-DCXX_FLAGS_CONFIG=${cxx_flags_config}"
        "-DGENERATOR=${CMAKE_GENERATOR}"
        "-DCMAKE_VERSION_STRING=${CMAKE_VERSION}"
        "-DSYSTEM_NAME=${CMAKE_SYSTEM_NAME}"
        "-DSYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}"
        "-DHOST_SYSTEM=${CMAKE_HOST_SYSTEM}"
        "-DTHREADING=${POLYFEM_THREADING}"
        "-DOPTIONS=${options}")

    # Once now, so the source exists for the first build; then before every
    # build of the target.
    execute_process(
        COMMAND "${CMAKE_COMMAND}" ${common_args} "-DBUILD_TYPE=${CMAKE_BUILD_TYPE}" -P "${script}"
        RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Generating the PolyFEM build identity failed (${result})")
    endif()
    add_custom_target(polyfem_build_info
        COMMAND "${CMAKE_COMMAND}" ${common_args} "-DBUILD_TYPE=${build_type}" -P "${script}"
        BYPRODUCTS "${output}"
        COMMENT "Refreshing the PolyFEM build identity"
        VERBATIM)
    add_dependencies(${target} polyfem_build_info)
    set_source_files_properties("${output}" PROPERTIES GENERATED TRUE)
    target_sources(${target} PRIVATE "${output}")
endfunction()
